### ISSUE TITLE
Basic Plots for the dataset graduates_germany.csv

### ISSUE THREAD

**Issue by mxs01** [mxs01/AnalysingStudentDevelopment#2]
# Description
To get a basic understanding of the dataset graduates_germany.csv we need some plots to get a basic understanding of the data and the underlying information

# Prerequisites
We need to separate the graduates from dropouts in graduates_germany.csv

# Tasks
- [x] plot for overall graduate numbers over the years
- [x] plot for difference between male and female students
- [ ] plot for dropouts
- [ ] plot for difference between male and female students (dropouts)
